name: Deploy VSCode Plugin

on:
  push:
    branches:
      - master

  release:
    types:
      - published
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: DevDependency
      run: |
        npm install -g mocha node vscode eslint-plugin parser test-cli test-electron eslint typescript
    - name: Dependency
      run: |
        npm install -g vsce axios comment-json
    - name: Package
      run: |
        vsce package
    - name: Deploy
      uses: actions/upload-artifact@v4
      with:
        name: vsix
        path: ./*.vsix
